### ISSUE TITLE
RabbitMQ docker doesn't work

### ISSUE THREAD

**Issue by leobewater** [PacktPublishing/Building-Distributed-Applications-in-Gin#4]
I couldn't get the rabbitmq docker localhost:8080 to work! Please help!

**Comment by mlabouardy** [comment]
Hello @leobewater its probably due to memory limit
you can increase the memory allocated to Docker engine & containers from Docker Desktop interface:
![image](https://user-images.githubusercontent.com/10320205/133081640-22424ae3-5cde-4f8e-8ddd-694ae73da3ed.png)
